title: Rahammetoela Toekiman also known as Tobiyo “Fuseteam” Kuujikai, xiaofuse, feishikong, Merkhad Luigton
#theme: jekyll-theme-cayman
remote_theme: feishikong/meet-the-team
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
