#!/bin/bash
function getLocalDirs(){
   awk '/Host/{print $2}' ~/.ssh/config
   readarray -t LocalDirs < <(awk '/LocalDirectory/{print $2}' ~/.ssh/fsconfig)
   for LocalDir in ${LocalDirs[@]}
   do
       basename $LocalDir;
   done;
}

_ssh() 
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    case "${cur}" in
        -*)
            COMPREPLY=( $(compgen -W "$(_parse_help $1)" -- ${cur}) );;
        *)
            COMPREPLY=( $(compgen -W "$(getLocalDirs)" -- ${cur}) );;
    esac

    return 0
}
complete -F _ssh sshmount
