#!/bin/bash
prefix="@prefix@/lib"
if [ "${prefix:0:1}" = "@" ]; then prefix=".";fi
source "${prefix}"/sshmountlib

_ssh()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    case "${cur}" in
        -*)
            COMPREPLY=( $(compgen -W "$(_parse_help $1)" -- ${cur}) );;
        *)
            if [ "${prev}" != "-u" ];
            then COMPREPLY=( $(compgen -W "$(getLocalDirs)" -- ${cur}) );
            else COMPREPLY=( $(compgen -W "$(getMountedDirs)" -- ${cur}) );
                fi;;
    esac

    return 0
}
complete -F _ssh sshmount
