#!/bin/bash
condir="$HOME/.ssh"
confile="$condir/fsconfig"

function fetchHostAttribute(){
    sed -n "/$1$/,/^Host/p" $confile|grep $2|awk '{print $2}'
}

if [ ! -d "$condir" ]; then
    mkdir $HOME/.ssh
fi

if [ ! -f "$confile" ]; then
    echo "Host hostname
        LocalDirectory  $HOME/sshfs
        RemoteDirectory /absolute/path/to/remote/directory" > $condir/fsconfig
fi
while getopts 'u:' flag; do
    case ${flag} in
        u) LD=`fetchHostAttribute $2 'LocalDirectory'`;
           [ -n $LD ] && fusermount -$flag $LD \
               || echo host missing LocalDirectory attribute in $confile
           exit;;
        *) echo 'please specify host';
            exit;;
    esac
done

if [ -z "$1" ]; then
    echo "please specify host";
    exit
fi

LD=`fetchHostAttribute $1 'LocalDirectory'`;
[ -z $LD ] && echo host missing LocalDirectory attribute in $confile \
    || RD=`fetchHostAttribute $1 'RemoteDirectory'`
[ -z $RD ] && echo host missing RemoteDirectory attribute in $confile\
    || sshfs $LD $1:$RD;
